/*
  # Add AI Generated Flag to Blog Posts

  1. New Columns
    - `ai_generated` (boolean, default false) - Flag to track if post was generated by AI
    - `generation_method` (text, nullable) - Track how the post was generated (manual, ai, expanded)

  2. Updates
    - Add index on ai_generated for faster queries
    - Update existing posts to set appropriate flags based on content analysis
*/

-- Add ai_generated flag to blog_posts table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'blog_posts' AND column_name = 'ai_generated'
  ) THEN
    ALTER TABLE blog_posts ADD COLUMN ai_generated boolean DEFAULT false;
  END IF;
END $$;

-- Add generation_method column to track how posts were created
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'blog_posts' AND column_name = 'generation_method'
  ) THEN
    ALTER TABLE blog_posts ADD COLUMN generation_method text DEFAULT 'manual';
  END IF;
END $$;

-- Add index for faster queries on ai_generated flag
CREATE INDEX IF NOT EXISTS idx_blog_posts_ai_generated ON blog_posts (ai_generated);

-- Update existing posts that were likely AI generated based on content patterns
UPDATE blog_posts 
SET ai_generated = true, generation_method = 'ai'
WHERE 
  content LIKE '%AI-powered%' 
  OR content LIKE '%artificial intelligence%'
  OR content LIKE '%machine learning%'
  OR content LIKE '%automation%'
  OR content LIKE '%digital transformation%'
  OR title LIKE '%AI%'
  OR title LIKE '%Artificial Intelligence%'
  OR title LIKE '%Automation%'
  OR title LIKE '%Digital Transformation%';